version: 0.2
phases:
  build:
  # made drom jenkins
    commands:
      - cd social-media-spring-main
      - mvn clean package
artifacts:
  files:
    - social-media-spring-main/Dockerfile
    - social-media-spring-main/target/social-media-0.0.1.-SNAPSHOT.war
    # 
  discard-path: yes

