server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://javafs22.cngwg4ynfse3.us-west-1.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
#  h2:
#    console.enabled: true